name: CI

on:
  push:
    tags:
      - v*

jobs:
  build-python-wheels-rocm:
    name: Build ROCm wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.4.0
        with:
          package-dir: python
          output-dir: python/wheelhouse
        env:
          CIBW_ENVIRONMENT_LINUX: ROCM_PATH=/opt/rocm LD_LIBRARY_PATH=/opt/rocm/lib/llvm/lib:$LD_LIBRARY_PATH
          CIBW_ENVIRONMENT_WINDOWS: CTRANSLATE2_ROOT='${{ github.workspace }}\install'
          CIBW_BEFORE_ALL_LINUX: python/tools/prepare_build_environment_linux_rocm.sh
          CIBW_BEFORE_ALL_WINDOWS: bash python/tools/prepare_build_environment_windows_rocm.sh
          CIBW_BEFORE_BUILD: pip install -r python/install_requirements.txt
          CIBW_ARCHS: auto64
          CIBW_SKIP: "*-musllinux_*"
          CIBW_REPAIR_WHEEL_COMMAND_LINUX: 'auditwheel repair -w {dest_dir} --exclude "/opt/rocm/lib/lib*" {wheel}'

      - name: Upload Python wheels
        uses: actions/upload-artifact@v6
        with:
          name: rocm-python-wheels-${{ runner.os }}
          path: python/wheelhouse

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-python-wheels-rocm]
    permissions:
      contents: write
    steps:
      - name: Download ROCm wheels
        uses: actions/download-artifact@v6
        with:
          pattern: rocm-python-wheels-*
          merge-multiple: true
          path: release-artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/*.whl
